### ISSUE TITLE
Register page form validation

### ISSUE THREAD

**Issue by saekort** [saekort/PFS-Scenariotracker#30]
The register page form validation seems to be 'off', you can press register even though you have not filled out all the required fields yet.

**Comment by FlavienKnuchel** [comment]
Seems working on my chrome / firefox, but get validated via html5 by the browser. Is that a problem with a precise browser/version or a general one? And what validation tech is used?

I could add a jquery.validate.js validation on this form, so that everybody with javascript or a recent browser is okay. I've been using this validate.js quite a lot these days

**Comment by saekort** [comment]
I would prefer we stick with Angular. I did add a proper ng-disable on it I think, but it seems to be bugged.

*digs in code*

```
ng-disabled="myForm.confirmEmail.$error.match || myForm.confirmPassword.$error.match || myForm.password.$error.pattern || vm.invalidpfsnumber"
```
That doesn't seem to work at the moment then. Documentation on ng-disabled: https://docs.angularjs.org/api/ng/directive/ngDisabled

Effectively it disables a element until the statement evaluates to true I believe. The entire app has this working, so there must be something off with this specific one.

**Comment by NieskeL** [comment]
I have a theory: the $error only seems to fire after I add random text to one of the required fields. After that, the buttons is disabled and the button is disabled.
Maybe there should be a condition that fires if the form is empty?
