### ISSUE TITLE
Author search is broken

### ISSUE THREAD

**Issue by saekort** [saekort/PFS-Scenariotracker#34]
See title.

**Comment by NieskeL** [comment]
I think the problem is in the API.

Postman gives me this error:
"<p>Unknown column 'authors_authors.name' in 'where clause'</p>"

Also, when I run the SQL code through the database it gives errors on the same line.

Something tells me that the V1 does not check the join-table in the database. Therefore it tries to get authors.name from the scenario table... which does not exist.

@saekort, if I remember correctly, I cannot edit the V1 from here. Want to look into this with me sometime next week?
